### ISSUE TITLE
.dat file missing after compiling on linux.

### ISSUE THREAD

**Issue by Alex313031** [k4zmu2a/SpaceCadetPinball#104]
Compiled on linux bullseye with cmake . and make, then went to the bin dir and ran ./SpaceCadetPinball. X11 window opens complaining about missing .dat file, but I can't find any .dat file anywhere in the cloned repo?

**Comment by 0x5066** [comment]
readme clearly states this

**Comment by k4zmu2a** [comment]
Game data is not included in this repo, it should be provided by the user.
This project supports data from multiple game releases, you can use any of them:
•	3D Pinball for Windows – Space Cadet
•	Full Tilt! Pinball, cadet table or demo

**Comment by 0x5066** [comment]
it might be better to close issues in the future and refer to the readme imo, saves you time

**Comment by k4zmu2a** [comment]
It is fine, readme is never a 100% solution, no matter how concise it is.

**Comment by CharlesThobe** [comment]
In case someone has chosen to extract the game files from the `I386` folder in the windows xp cd via:
```
expand -r pinball*.* sound*.wa_ font.da_ PINBALL.CH_ D:\Pinball
```
where the current directory is the `I386` folder and `D:\Pinball` is the target location. Note: the target directory has to exist.
then you're gonna have rename all the extracted files to be uppercase since this command extracts the files in lowercase names, and the project expects all the files to be in uppercase (necessary in all operating systems except windows)
