### ISSUE TITLE
add higher-res table from full tilt pinball

### ISSUE THREAD

**Issue by RiedleroD** [k4zmu2a/SpaceCadetPinball#122]
since _3D Pinball: space cadet_ is just a slightly modified version of the space cadet version of _full tilt pinball_, I thought you could take the CADET.DAT from the original, which has a 1024x768 version of the table and copy it over or something.

**Comment by tomrow** [comment]
That's already a feature, make sure though that you don't have both PINBALL.DAT and CADET.DAT in the same folder.

**Comment by k4zmu2a** [comment]
CADET.DAT support is already done, but I wouldn’t not call it copying over.
Think of this in terms of game engine and game data.
My game engine supports game data from both FT and 3DPB.
In order to play, you are replacing the original engine with my version.

**Comment by RiedleroD** [comment]
*ohhh* it's optional to get the CADET.DAT - see, I just installed it from the AUR and assumed it copied everything it needed over. Maybe a popup at first startup to notify the user of the missed file would be helpful?

**Comment by k4zmu2a** [comment]
I distribute the project without any game data. Users are free to choose their preferred data.

Of course, 3rd party packages don’t have to follow this.
That AUR package includes only 3DPB data, that is probably by design.
It could have just as easily included FT data, or both. 
Or maybe there could be a separate package with FT, the possibilities are endless.
I hope you can see that this packaging situation came through no fault of mine.

**Comment by haarp** [comment]
It would be cool to be able to merge both versions. I, like many others probably, enjoy the nostalgia of the Windows version score panel, but the higher-res FT table just looks better.

**Comment by k4zmu2a** [comment]
A data merge like that is technically possible.
But it will only work with the lowest table resolutions.
3DPB assets would have to scaled for higher resolutions.
This could be a luxury feature, to be attempted after everything else.
