### ISSUE TITLE
Bug: if Secret Mission is aborted, wormhole lights still flash

### ISSUE THREAD

**Issue by dobragab** [k4zmu2a/SpaceCadetPinball#124]
Repro steps, although I haven't verified with cheat mode yet:
* Start a Secret Mission, when you have to shoot the Yellow, then Red, then Green wormhole in order.
* As a first step, the arrow light for the Yellow wormhole will start flashing.
* Wait until the mission is aborted due to fuel. Mission aborted, refuel the ship.
* The white "Refuel" arrow will start flashing, but the Yellow wormhole will keep flashing.

**Comment by k4zmu2a** [comment]
This bug is from the original 3DPB.
Fixed by adding wormhole lights reset in SelectMissionController code 66.

**Comment by k4zmu2a** [comment]
The are three stages of secret mission, each uses different wormhole and lights.
It makes sense to fix mission abort for all of them.

About FT: I don’t know but am curious as well.
I can’t easily do it without hidden test and my decomp does not cover that part yet.
If I figure it out, I’ll write it here.

**Comment by k4zmu2a** [comment]
FT has this bug as well, as expected.

Some fun facts about FT that I learned:
FT has fully functional hidden test, it is entered with tab instead of space: “hidden\ttest”.
FT runs uncapped at blistering 30000+ UPS, mouse cheat does not work in such conditions.
I worked around this issue by injecting sleep(8) into main loop with CheatEngine.

**Comment by dobragab** [comment]
Cool! I'm not surprised either :)
Thanks!
