### ISSUE TITLE
Is there a way to get functionality from 1.1 version working?

### ISSUE THREAD

**Issue by DarkLord76865** [k4zmu2a/SpaceCadetPinball#177]
Hi,
as you probably know, with Full Tilt!, a newer version 1.1 of the game was released. The changes weren't major, but what I like about that version is that entry lights don't get turned off when a ball passes over already lit light. I can see in README that you did analyse this version (CADET.exe, I compared SHA). So is there any way to get that working?

Thanks,
great work done!

P.S. Why not include game data/resource files here? I know about licensing stuff, but does anybody really care about this game anymore? I highly doubt that it would bother anyone if those were included here. There is an original disc image on Internet Archive from where those files can be easily/safely acquired. (That's where I got my CADET.exe to compare to yours also). I can even do it and open PR if you'd like.

**Comment by k4zmu2a** [comment]
Hello.

Are you talking about these specific light rollovers?
![image](https://github.com/k4zmu2a/SpaceCadetPinball/assets/33288308/49c2a3d5-f137-4763-896f-72be33275ab6)
They already have this “no toggle off” feature.
It only shows up when running with FT game data, 3DPB game data uses its own original logic.

This particular FT/3DPB difference comes from the code area called control, which is responsible for missions and table component interactions.
It is my goal to have control that accurately represents both FT and 3DPB behaviors. Currently I am working on FT Cadet control, work on 3DPB is complete.
For each game logic difference, my version of the game chooses which behavior to use based on the loaded game data.
In the future, I can see an introduction of game mode editor that would let users pick and choose game behaviors regardless of loaded game data type.


Not including original game data was my intention from the very begging of the project.
I am sticking with that diction for now, so no need to make PRs with game data.
Obviously, this restriction does not apply to game distributions made by third parties.

**Comment by k4zmu2a** [comment]
This “no toggle off for rollover lights” feature is not present in latest release V2.0.1; it is a relatively recent development.
This feature is not controlled by options.
To get it, you just need to run the game with FT cadet game data instead of 3DPB game data.

If you want, I can share with you the latest dev build for Windows. 
For other platforms, I recommend building it yourself.

**Comment by DarkLord76865** [comment]
Hi,
thanks for everything. I would appreciate if you shared the build (I haven't worked with C++ before so I don't really know how to compile it myself right now, though that will change in the near future 😃). Keep up the good work!

**Comment by k4zmu2a** [comment]
Here you go: 
[SpaceCadetPinball_x86_V2.1.0Dev.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/11849744/SpaceCadetPinball_x86_V2.1.0Dev.zip)

About game resources:
Editing game data is non-trivial because there is no public editor for the format used.
Extending the game with support for new table resolutions is even more difficult.
I might make an editor for pinball .dat files, but only after all currently unfinished major goals.

**Comment by DarkLord76865** [comment]
Thanks!

Yes, I understand that .dat files are tough to edit. I was thinking about it, and I think it may be possible to extract that data to some other format, that is easier to edit, and write a new piece of code that loads data from there instead of .dat files. Of course, that is a lot of work. After I learn C/C++, I might contact you again to help work on whatever needs to be done. This is a great project, I love Pinball. I'm closing this issue now, you helped me very much.

Thanks again!
