### ISSUE TITLE
ARM Version for Linux?

### ISSUE THREAD

**Issue by Sweeistaken** [k4zmu2a/SpaceCadetPinball#183]
Hi, I just wanted to try this game on my Raspberry Pi. Is there any chance you could release an ARM version of this game for Linux?

**Comment by k4zmu2a** [comment]
Hello.
Unfortunately, no, I do not provide pre-compiled binaries for Linux.

You could try flathub package, since it has aarch64 build:
https://flathub.org/apps/com.github.k4zmu2a.spacecadetpinball
Alternatively, compile it yourself, either cross or on the Pi itself.
This project is relatively light to compile, Pi should be able to handle it.

**Comment by Sweeistaken** [comment]
@k4zmu2a I am using the Pi 2, which uses armhf instead of aarch64, where and how do i compile it?

**Comment by k4zmu2a** [comment]
I am not familiar with RPI stuff, armhf is most likely 32-bit arm.
So, your choices are:
1)	Compile the game on RPI itself.
2)	Cross-compile the game on your desktop non-arm PC.

In both cases, you will have to install build tools needed to build the game.
Cross-compilation is more difficult, I recommend starting with option 1.
