### ISSUE TITLE
Cannot compile X64-release on VS2019 due to cmake errors

### ISSUE THREAD

**Issue by Sunlitspace542** [k4zmu2a/SpaceCadetPinball#19]
I can build x64-debug just fine, but release gives cmake errors. (see screenshot)
![image](https://user-images.githubusercontent.com/35207254/135741716-dcd09735-597b-448a-91aa-14bc38d6f611.png)

**Comment by k4zmu2a** [comment]
SDL2_LIBRARY variable is supposed to be a list, containing paths to SDL2.lib and SDL2main.lib.
In your case it has only one path, probably to SDL2.lib.
I don’t know why that happened, debug and release builds should use the same lib folder.

I simplified the build by disabling SDL2main link, because it was not actually needed.
This might help you.
