### ISSUE TITLE
Only one Sound playing at a time

### ISSUE THREAD

**Issue by Kirschi94** [k4zmu2a/SpaceCadetPinball#30]
The original Pinball was able to play more than one sound at a time, while this version interrupts the running sound with a new one.

**Comment by k4zmu2a** [comment]
You are welcome. I strive to achieve a high overall quality in this project.

Voices is a DWORD value.
You put the number of channels into it, in range [1, 8].

When this key does not exist, the game uses default value of 8.
Since you initially did not have it, your problem must be somewhere else.

Try the original WinXP pinball, this voices option should also affect it.
Expected result: without the key or set to 8 - all ok; set to 1 – one sound at a time.

I don’t have any other ideas that might help, and I can’t reproduce this (tried on Win7 and 10).
This needs to be debugged on the machine where it happens.
If you are able, debug it yourself. Relevant classes are Sound and WaveMix.

![image](https://user-images.githubusercontent.com/33288308/136948905-32fd7197-5464-4c3a-94c3-f9a339e89dbf.png)
