### ISSUE TITLE
Music cannot be turned off

### ISSUE THREAD

**Issue by romwer** [k4zmu2a/SpaceCadetPinball#37]
Sound can be turned off by selecting the related menu point under Options. But for Music, it keeps playing. I use Chrome version 94.0.4606.81 (Official Build) (64-bit).

**Comment by romwer** [comment]
Oh sorry. I was indeed relating to the browser version at https://alula.github.io/SpaceCadetPinball/

**Comment by markusbkk** [comment]
Just found this.

It seems related to the addition of TinySoundFont inside the Emscripten port.
I'm gonna take a look tomorrow. 

I [forked](https://github.com/markusbkk/SpaceCadetPinball-WASM) the Emscripten port since there wasn't any activity and the original repo doesn't have a bug tracker.

**Comment by k4zmu2a** [comment]
My guess was that internal MIDI renderer was simply not hooked up to the UI.
But anyway, this source port issue is not a concern for the main project.

**Comment by markusbkk** [comment]
> My guess was that internal MIDI renderer was simply not hooked up to the UI.

Yea. That's my understanding too.
I'll look into it this weekend. Will probably replace the sound font, too. Since there's enough libre ones without putting this project into the Age of Pirates.

>  But anyway, this source port issue is not a concern for the main project.

True. I'm very thankful for this project, btw. Been waiting to sink my teeth into something for a long time.

BTW: stech11845 renamed his account and deleted all his previous work, so whatever Web port existed before can no longer be found on GitHub.

**Comment by k4zmu2a** [comment]
Emscripten port issue.
