### ISSUE TITLE
Do you accept cross-platform and feature patches?

### ISSUE THREAD

**Issue by mariotaku** [k4zmu2a/SpaceCadetPinball#39]
Kudos to this awesome project!

I have start working on porting this program to webOS TV: https://github.com/webosbrew/SpaceCadetPinball . Which ~hides some options on TV~ (I see your comments to other source ports, so I'll leave platform specific parts out of the scope.) and will add some features, for example game controller support.

Do you accept such patches, or wish to keep this project as vanilla as possible?

**Comment by k4zmu2a** [comment]
Glad that you like my project.

I am not accepting:
•	Any source ports
•	Code with liberal use of #ifdef

The idea is to keep the code simple, easy to compile and port.
No source ports on the basis of me being unable to test and maintain them.

Joystick support is in scope of this project. 
FT had joystick support, so it’s even thematically appropriate.
It is not in yet simply because I don’t own a joystick.
I was planning to add it eventually.

I will accept your joystick patch, without gamecontrollerdb.txt part.
Hardcoded mapping to Options.Key is fine as a first step.
Eventually I plan to add joystick and mouse mapping to control dialog.

**Comment by mariotaku** [comment]
Thank you! I have added patch without platform specific part here: https://github.com/k4zmu2a/SpaceCadetPinball/pull/42 .
Another suggestion: How about adding this rule to README, or CONTRIBUTE?

**Comment by k4zmu2a** [comment]
I was not really expecting any major PRs to be honest.
I will try to add CONTRIBUTE.

**Comment by k4zmu2a** [comment]
Question was answered.
